# Generated by Django 4.0.6 on 2022-08-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.TextField()),
                ('name', models.TextField()),
                ('course_number', models.IntegerField()),
                ('group_number', models.IntegerField()),
                ('teacher', models.TextField()),
                ('start_time', models.TextField()),
                ('end_time', models.TextField()),
                ('first_day', models.IntegerField(choices=[(0, 'Saturday'), (1, 'Sunday'), (2, 'Monday'), (3, 'Thursday'), (4, 'Wednesday'), (5, 'NotSet')], default=5)),
                ('last_day', models.IntegerField(choices=[(0, 'Saturday'), (1, 'Sunday'), (2, 'Monday'), (3, 'Thursday'), (4, 'Wednesday'), (5, 'NotSet')], default=5)),
            ],
        ),
    ]
