# Generated by Django 4.0.6 on 2022-08-03 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='last_day',
            new_name='second_day',
        ),
    ]
