# Generated by Django 4.0.6 on 2022-08-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_alter_course_end_time_alter_course_first_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moredetail',
            name='avatar',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
