# Generated by Django 4.0.6 on 2022-08-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_moredetail_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moredetail',
            name='avatar',
            field=models.ImageField(upload_to=''),
        ),
    ]
