# Generated by Django 4.0.6 on 2022-08-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_alter_moredetail_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moredetail',
            name='avatar',
            field=models.ImageField(default='./static/first/avatar.jpg', upload_to='images/'),
        ),
    ]
